### PR TITLE
Added missing labels for U702 and U711

### PR DESCRIPTION
**Pull request by kavanoz64**
Updated the Gerbers and the preview image as labels for 2 chips were missing on the silkscreens.

### CODE REVIEW

**Comment by Acill** [comment]
Thanks for the updates and continued hard work.

**Comment by kavanoz64** [comment]
Did you close my pull request without merging? I still see the old files in your repo.

**Comment by Acill** [comment]
I merged. Did it mess up?

**Comment by Acill** [comment]
Old files are still there bitnotbadded a new folder with yours. I made a
note on front page tobise yours as well. I can completely remove the old
folders of you think is better?

**Pull request closed without merging**
